name = "fed-migration"
main = "src/index.ts"
compatibility_date = "2025-07-20"
workers_dev = false

routes = [
    { pattern = "oldfed.abbaspour.net", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
